# Generated by Django 3.2 on 2021-05-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0002_event_attendees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='difficulty',
            new_name='gamer',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_limit',
            new_name='number_of_player',
        ),
        migrations.AddField(
            model_name='game',
            name='maker',
            field=models.CharField(default=99, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='skill_level',
            field=models.IntegerField(default=88),
            preserve_default=False,
        ),
    ]
