# Generated by Django 3.2 on 2021-05-05 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0003_auto_20210505_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='number_of_player',
            new_name='number_of_players',
        ),
    ]
