# Generated by Django 3.2 on 2021-05-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0006_auto_20210505_1929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Event',
        ),
    ]
